# Generated by Django 5.1.1 on 2024-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_phone_number',
        ),
    ]
