# Generated by Django 5.1.1 on 2024-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_seller_gst_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_bank_account',
            new_name='seller_bank_acc_type',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_bank_ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
