# Generated by Django 5.1.1 on 2024-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_rename_seller_bank_account_seller_seller_bank_acc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/business_logo'),
        ),
    ]
