# Generated by Django 5.1.1 on 2024-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_seller_seller_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
