# Generated by Django 5.1.1 on 2024-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
