# Generated by Django 5.1.1 on 2024-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_seller_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(),
        ),
    ]
