# Generated by Django 5.1.1 on 2024-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_tags_alter_category_seller_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
