# Generated by Django 5.1.1 on 2024-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic_back',
            field=models.ImageField(upload_to='products/product_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_front',
            field=models.ImageField(upload_to='products/product_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_third',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_photo'),
        ),
    ]
