# Generated by Django 5.1.1 on 2024-10-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_product_pic_back_and_more'),
        ('seller', '0007_seller_seller_linkedin_url_seller_seller_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_back',
            field=models.ImageField(upload_to='products/product_photo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_photo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_front',
            field=models.ImageField(upload_to='products/product_photo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_third',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_photo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
