# Generated by Django 5.1.1 on 2024-10-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_category_alter_product_created_at_and_more'),
        ('seller', '0007_seller_seller_linkedin_url_seller_seller_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('seller', 'category_name')},
        ),
    ]
