# Generated by Django 5.1.1 on 2024-10-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Active', max_length=15),
        ),
    ]
